---
version: 2
plan:
  project-key: SPCT
  key: ROCKET
  name: Build the rockets

stages:
  - Build the rocket stage:
    - Build

Build:
  tasks:
    - script:
        - mkdir -p falcon/red
        - echo wings > falcon/red/wings
        - echo 'Built it'
  requirements:
     - isRocketFuel
  artifacts:
     - name: Red rocket built
       pattern: falcon/red/wings
